# -*- coding: utf-8 -*-
"""Assignment - 10/01 (Password Reminder

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pc0HZ0FUeDNx94AxVpAZEpewlbuKlHqR
"""

name= input("Please type your name: ").capitalize()
if name == "Joseph":
  print("Hello, Joseph! The password is : W@12")
else:
  print("Hello, Amina! See you later.")