# -*- coding: utf-8 -*-
"""Assignment - 10/02 (Covid-19 Risk with If Statements)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pc0HZ0FUeDNx94AxVpAZEpewlbuKlHqR
"""

print("  Please give answers just with 'Yes or No' "  )
print("")

age = input("Are you a cigarette addict older than 75 years old?  Yes/No ").lower()
chronic = input("Do you have a severe chronic disease?  Yes/No ").lower()
immune = input("Is your immune system too weak?  Yes/No ").lower()
print("")

if age =="yes":
    age=True
elif age!="yes":
    age=False

if chronic =="yes":
    chronic=True
elif chronic!="yes":
    chronic=False

if immune =="yes":
    immune=True
elif immune!="yes":
    immune=False
print("")
print(age, chronic, immune)
print("")
if age and chronic and immune ==True:
    print("You are in risky group")
else:
      print("You are not in risky group")